### ISSUE TITLE
Change bibtex accent encoding from \v{ to {\v syntax because of ordering

### ISSUE THREAD

**Issue by vidiecan** [ufal/lindat-repository#112]
http://tex.stackexchange.com/questions/57743/how-to-write-%C3%A4-and-other-umlauts-and-accented-letters-in-bibliography/57745#57745

**Comment by vidiecan** [comment]
Inspect if the sorting is really different for 
\{v a}
and
\v{a}

**Comment by vidiecan** [comment]
see also http://stackoverflow.com/questions/1635788/different-encoding-of-latex-and-bibtex-files for specific problems when using \v{ instead of {\v{ or {\v

**Comment by foxik** [comment]
The ordering is really different.

Consider the following `test.tex`:
```
\documentclass{article}

\begin{document}
\cite{a}\cite{b}\cite{c}\cite{d}
\bibliographystyle{plain}
\bibliography{test}
\end{document}
```
and the following `test.bib`:
```
@inproceedings {a,
  title={Biblio a},
  author={\v{C}}
}

@inproceedings {b,
  title={Biblio b},
  author={{\v{C}}}
}

@inproceedings {c,
  title={Biblio c},
  author={vb}
}

@inproceedings {d,
  title={Biblio d},
  author={vd}
}
```

After running `pdflatex test; bibtex test` the following `test.bbl` is created:
```
\begin{thebibliography}{1}

\bibitem{b}
{\v{C}}.
\newblock Biblio b.

\bibitem{c}
vb.
\newblock Biblio c.

\bibitem{a}
\v{C}.
\newblock Biblio a.

\bibitem{d}
vd.
\newblock Biblio d.

\end{thebibliography}
```

As you can see, the entry `a` and `b` should be next to each other, but they are not. Moreover, as `a` is between `c` and `d`, it is really being sorted as `vc`.

**Comment by vidiecan** [comment]
thanks for the details!

**Comment by vidiecan** [comment]
Seems there exist (la)tex styles relying on the {\ format!

**Comment by vidiecan** [comment]
closing, see https://github.com/ufal/lindat-dspace/issues/76 in the new lindat repository version
