### ISSUE TITLE
Search more attributes via the main search element

### ISSUE THREAD

**Issue by stranak** [ufal/lindat-repository#18]
Currently there is no simple way to search for many things. E.g. "Tamil data". It is possible to achieve this, but it is highly unintuitive.

I propose to search (almost) everything and then filter by attributes. This filtering also needs improvements, just try to find those records that include Tamil language and see.

**Comment by kosarko** [comment]
The issue with searching/browsing/filtering by language is that we actually store only the iso code. Which is great for exports/automated processing, but not so great for browsing by people. We've tried to make this more feasible by translating the codes in the front end with js. That probably have led to some of the unintuitivnes.

I've wrote few lines about what is indexed [Search, browse & filter](https://github.com/ufal/lindat-repository/wiki/Search,-browse-&-filters)

---

PR #92 adds special handling for the iso codes when indexing. As a result you can use both the iso code and language name in the fulltext search. Filter and browse index now contain the full names, so it's hopefully more intuitive to use them.

Both SOLR and browse indexes need to be rebuild, when this is deployed
