### ISSUE TITLE
Generate lists of published data/tools for UFAL web pages (Drupal)

### ISSUE THREAD

**Issue by stranak** [ufal/lindat-repository#24]
See how the list of user's publications can be automatically generated on his homepage by using a custom block, e.g. `[biblio]stranak[/biblio]`

Generate published data/tools in a similar manner. Ideally dynamically (via REST API?), but worst case, use the same mechanism Dan is using for Biblio exports. Consult Honza Ptacek (Drupal admin).

**Comment by vidiecan** [comment]
https://github.com/ufal/lindat-dspace/issues/79
