### ISSUE TITLE
Show Size

### ISSUE THREAD

**Issue by stranak** [ufal/lindat-repository#43]
E.g. http://hdl.handle.net/11234/1-1457

META-Share attributes for size (number and units) are filled in, but they are only visible in "full record". They should be visible in the default short record too. Nobody but us knows those attributes are there.

**Comment by kosarko** [comment]
This only works with new submissions, ie. items having local.size.info. Should be modified to work with the older ones, too

**Comment by kosarko** [comment]
#90 which also displays all the sizes (size info is repeatable)
