### ISSUE TITLE
Remove static.js from 

### ISSUE THREAD

**Issue by vidiecan** [ufal/lindat-repository#62]
sources\dspace\modules\xmlui\src\main\webapp\themes\UFAL\lib\discojuice\
see https://svn.ms.mff.cuni.cz/redmine/issues/423

**Comment by kosarko** [comment]
pull request #89  

The file is no longer needed. It was just a backup of discojuice jsonp file. In case the discojuice feeds are unavailable we already use shibboleth to generate this.
