### ISSUE TITLE
Github (and more?) code archiving 

### ISSUE THREAD

**Issue by stranak** [ufal/lindat-repository#7]
See https://guides.github.com/activities/citable-code/ 

I am thinking about something **much** simpler: Does Github API give us enough info to create one additional dialog if we see somebody is creating a record for Github-hosted code? 

*Offer list of releases, tagged versions of code and the latest commit and ask which of these to archive, (or maybe none).*

This is part of a bigger issue on how to cite code, but we could offer this choice to begin with.

**Comment by vidiecan** [comment]
https://github.com/ufal/lindat-dspace/issues/78
